
FROM python:3.10-slim

WORKDIR /app

# copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy app files (templates/static included)
COPY . .

# expose port used by app.py (Flask default 5000)
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000

EXPOSE 5000


CMD ["python", "app.py"]
